### ISSUE TITLE
低识别率然后字幕中会提示“adjust_required”

### ISSUE THREAD

**Issue by latinisation** [Ayanaminn/N46Whisper#100]
已经扣人声处理，且对大部分非日语部分消音了，但是识别度（65%）却不如同样扣人声但未消音的音频识别率高（82%）
![image](https://github.com/Ayanaminn/N46Whisper/assets/26472091/41e9dfbb-6215-43bd-aa01-7fe8dbe12668)
试了几次均是如此，请问这会是什么问题呢？是本身视频就有问题吗？
![image](https://github.com/Ayanaminn/N46Whisper/assets/26472091/1ad7b013-78a6-4ad2-823c-ec941bfe010f)
![image](https://github.com/Ayanaminn/N46Whisper/assets/26472091/8757ef0b-e5ac-409a-97d1-cd0753fdd3c2)
1是未消音，2是消音，开头结尾都不一样。而且未消音的音频字幕到了17分钟左右往后就没有“adjust_required”报错了。这可能是什么原因呢？有谁遇到过吗？

**Comment by Ayanaminn** [comment]
adjust_required是因为分割句子这个选项吧，后面不满足分割条件就没有这个提示了
识别度这个问题我感觉现在还是有点玄学

**Comment by latinisation** [comment]
这样吗 那我试试不分行
