### ISSUE TITLE
Google Colab Runtime Error

### ISSUE THREAD

**Issue by CooperWang0912** [Ayanaminn/N46Whisper#108]
最近ctranslate2的更新会导致运行Google Colab的时候出现runtime error，解决方法是在run whisper的单元格import里加上这行
`!pip install ctranslate2==4.4.0`

原issue的链接：[WhisperX in Google colab Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so} ](https://github.com/m-bain/whisperX/issues/901)

另外，因为本Repo已经不再更新/维护，我会把这个bug fix放在我自己的fork里，链接在这里：
[N46Whisper Fork](https://github.com/CooperWang0912/N46Whisper)

**Comment by Ayanaminn** [comment]
感谢您，方便的话可以提个PR吗
虽然不打算主动更新了，但是小毛病解决下能让有需要的人继续用还是没问题的。
谢谢！

**Comment by CooperWang0912** [comment]
没问题，PR我刚刚提交好了
