### ISSUE TITLE
加载完模型，进行到识别中Transcribe in progress...时会话因不明原因而导致崩溃

### ISSUE THREAD

**Issue by easyjik** [Ayanaminn/N46Whisper#109]

**Comment by CooperWang0912** [comment]
解决方法见[这里](https://github.com/Ayanaminn/N46Whisper/issues/108)

**Comment by easyjik** [comment]
> 解决方法见[这里](https://github.com/Ayanaminn/N46Whisper/issues/108)

感恩！已解决
