### ISSUE TITLE
 'use_drive' is not defined

### ISSUE THREAD

**Issue by Mikrokosmos12** [Ayanaminn/N46Whisper#110]
大佬，问个问题，这个怎么解决啊，前面就上传文件，然后依次点击下面的运行，结果运行whisper就出现下面的情况，然后就会话崩溃
![屏幕截图 2024-10-29 204312](https://github.com/user-attachments/assets/872e3471-413b-43a8-8ba6-3a8084985fba)
再运行就这样了，按照最新的那个回答在import 那里加了那个语句还是不行
![屏幕截图 2024-10-29 204054](https://github.com/user-attachments/assets/88d84cf3-95a4-435a-be15-52696d750346)

**Comment by Ayanaminn** [comment]
你好，我没有复现这个错误。可能需要更多信息才能判断原因。
此外如果在转录时出错，需要从头执行一遍，不能仅仅重新执行转录单元格。

**Comment by Mikrokosmos12** [comment]
> 你好，我没有复现这个错误。可能需要更多信息才能判断原因。 此外如果在转录时出错，需要从头执行一遍，不能仅仅重新执行转录单元格。
谢谢大佬，我上传的音频格式是m4a，应该不支持，所以才有上面的问题，刚才我上传mp4文件就正常了，顺便问下支持哪些格式的音频。感谢

**Comment by Ayanaminn** [comment]
> > 谢谢大佬，我上传的音频格式是m4a，应该不支持，所以才有上面的问题，刚才我上传mp4文件就正常了，顺便问下支持哪些格式的音频。感谢

常见的媒体格式都支持，包括mp3,m4a,flac,aac,wav,mp4,mkv,ts,flv，记得上传音频选择audio，上传视频选择video。

**Comment by Mikrokosmos12** [comment]
> > > 谢谢大佬，我上传的音频格式是m4a，应该不支持，所以才有上面的问题，刚才我上传mp4文件就正常了，顺便问下支持哪些格式的音频。感谢
> 
> 常见的媒体格式都支持，包括mp3,m4a,flac,aac,wav,mp4,mkv,ts,flv，记得上传音频选择audio，上传视频选择video。

奇怪，昨晚上传m4a，后面也有检查有没有选择audio，但就是不行，不过今天就都可以了【哭笑】总之谢谢大佬回复
