### ISSUE TITLE
[feature]设置多个音频文件，自动进行语音识别

### ISSUE THREAD

**Issue by bushnerd** [Ayanaminn/N46Whisper#15]

**Comment by Ayanaminn** [comment]
是指批量处理吗

**Comment by bushnerd** [comment]
嗯，是的。不过这个涉及到进行一次语音识别后，要释放资源进行下一次语音识别，我也正在研究。

**Comment by 41889732** [comment]
你好，我添加了在谷歌网盘选择文件模式下的工作流程添加了连续上传并处理多个文件的功能，并提交了一个pull request：https://github.com/Ayanaminn/N46Whisper/pull/38

**Comment by Ayanaminn** [comment]
感谢PR [#38](https://github.com/Ayanaminn/N46Whisper/pull/38), 加上今天已经改为在faster-whisper的基础上来部署脚本， 应该可以做到批量处理文件而不会遇到资源不够的问题了。
