### ISSUE TITLE
能否本地使用？

### ISSUE THREAD

**Issue by xmhwws** [Ayanaminn/N46Whisper#16]
发现上传谷歌云盘太慢了，也很耗梯子，能否支持直接在windows电脑上处理？

**Comment by Ayanaminn** [comment]
参见[常见问题](https://github.com/Ayanaminn/N46Whisper/blob/main/FAQ.md).
在本地使用Whisper有多种实现方案或者工具了，使用Colab还是考虑到借助平台为多数人提供免费的GPU支持以便最大限度的利用Whisper的识别能力。
