### ISSUE TITLE
RateLimitError

### ISSUE THREAD

**Issue by heyklyee** [Ayanaminn/N46Whisper#20]
RateLimitError                            Traceback (most recent call last)
[<ipython-input-11-140066ee228f>](https://localhost:8080/#) in translate(OOO0OO000O0OOO0OO, OO00O0OOOO00O0O00)
     33         try :#line:27
---> 34             OO00OO000O0O000O0 =openai .ChatCompletion .create (model ="gpt-3.5-turbo",messages =[{"role":"user","content":f"Please help me to translate,`{OO00O0OOOO00O0O00}` to {OOO0OO000O0OOO0OO.language}, please return only translated content not include the origin text",}],)#line:37
     35             O00O000000000O00O =(OO00OO000O0O000O0 ["choices"][0 ].get ("message").get ("content").encode ("utf8").decode ())#line:44

12 frames
RateLimitError: You exceeded your current quota, please check your plan and billing details.

During handling of the above exception, another exception occurred:

RateLimitError                            Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    680         stream_error = stream and "error" in resp.data
    681         if stream_error or not 200 <= rcode < 300:
--> 682             raise self.handle_error_response(
    683                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    684             )

RateLimitError: You exceeded your current quota, please check your plan and billing details.

为什么会出现这个啊  就一个两分钟的视频  而且前面日语的字幕也只扒了三句出来

**Comment by Ayanaminn** [comment]
你看看你的额度是不是用完了： https://platform.openai.com/account/usage

**Comment by heyklyee** [comment]
> 你看看你的额度是不是用完了： https://platform.openai.com/account/usage

看了下 确实是没额度了  不知道为什么账号没有免费额度 可能活动结束了
现在也没有充值手段 暂时没法测试了
