### ISSUE TITLE
电话号码和 callmebot 的 api key 泄露了

### ISSUE THREAD

**Issue by fireattack** [Ayanaminn/N46Whisper#24]
![image](https://user-images.githubusercontent.com/4130991/226334787-c7f1ca54-3cec-4c95-bf52-691012e5a4ef.png)

**Comment by Ayanaminn** [comment]
稍后会加个注释在这里

**Comment by Ayanaminn** [comment]
ef2e1b5244fbc7252b90b1bea776c83e67d584e4
