### ISSUE TITLE
对【实验功能】的期待

### ISSUE THREAD

**Issue by Schafpuppi** [Ayanaminn/N46Whisper#28]
1. 希望在【实验功能】AI文本翻译中，加入其他翻译目标语言的选项（比如英文）。
2. 也希望在【实验功能】中，加入上传已有的ass文件，然后进行自动翻译的功能。

**Comment by Ayanaminn** [comment]
这两个应该都是对其他用户也比较实际的需求，会尽快添加

**Comment by Ayanaminn** [comment]
8e1d796ff28896a4b8704728bc6b730a2addc8d6
已经更新，欢迎测试
