### ISSUE TITLE
关于AI翻译模块能否单独添加一个上传字幕文件的功能。

### ISSUE THREAD

**Issue by WebelyTwilight** [Ayanaminn/N46Whisper#30]
转录完之后会有云端的实时保存，但是ai翻译的部分坏了的话需要从whisper重新转录开始，就很麻烦。
要是ai翻译的部分可以单独添加一个上传字幕文件的功能的话会避免一些colab算力浪费。

**Comment by ShadowClone8848** [comment]
确实，毕竟会出错或者断开，要从头执行一遍也太浪费了

**Comment by Ayanaminn** [comment]
我自己不太用AI翻译这部分功能所以没能想到这方面的问题
会尽快加上这个功能

**Comment by Ayanaminn** [comment]
8e1d796ff28896a4b8704728bc6b730a2addc8d6
已经更新，欢迎测试
