### ISSUE TITLE
export_srt设置为Yes但是没有下载srt文件（下载能否单独提取成一个单元格？）

### ISSUE THREAD

**Issue by yy35959199** [Ayanaminn/N46Whisper#35]
![image](https://user-images.githubusercontent.com/37442303/230256150-4f7a2896-ee4b-4895-913e-240f60ccdfda.png)
![image](https://user-images.githubusercontent.com/37442303/230256226-c446fa30-fcbc-49e4-a7e6-358a5b9ee292.png)
![image](https://user-images.githubusercontent.com/37442303/230256242-001a86c6-006a-48c5-82cb-b5f19e3dfae1.png)
图1：已经设置成yes
图2：代码是新的
图3：只收到了ass的下载请求
OTZ不清楚怎么回事……能否修改成，程序运行成功后，不在这个单元格里下载，而是把“下载”这个步骤单独抽取成一个单元格？这样的话就算下载过程中失败了，只要不刷新页面就可以再下载一次，不然想要重新下载就只能从头跑一次语音转文字……

**Comment by Ayanaminn** [comment]
同时下载多个文件chrome会弹出个窗口要你允许
然后ass和srt生成后其实都储存在colab当前目录的，左边打开文件列表手动下载也可以
