### ISSUE TITLE
出错&功能建议

### ISSUE THREAD

**Issue by wurarara** [Ayanaminn/N46Whisper#4]
~~不是做翻译的~~，偶然发现的笔记本，所以功能建议可以酌情考虑再决定是否增加~
使用笔记本后有两点问题：
> 在云盘新建文件夹voice，并上传音频文件到其中，使用笔记本读取不到voice文件夹中的音频。（我也没看见select按钮，可能是没选到音频的缘故）
> 使用本地上传文件，上传了三个音频文件，最后自动下载了第一个，其余被忽略了。

功能建议：
> 我想要批量转化音频，1k-10k这个样子，我希望可以让笔记本读取云盘内每一文件夹下的所有音频，然后按顺序批量转换。
> 能不能增加一个导出为txt的选项？txt只导出文本~
```
原本这样
--------------
[0:0:0:1:0]　お願いします。
[0:0:0:1:0]　お願いします。
[0:0:0:1:0]　お願いします。
--------------
txt导出为这样
--------------
お願いします。
--------------
（当然，，这一点没什么必要，我也可以本地转换ass为txt，然后去除多余参数）
```

> 还有就是批量下载上千个txt有点头疼，如果能直接在colab笔记本的show code界面看到转换后的结果，那直接复制就好了，不用下载了

**Comment by Ayanaminn** [comment]
>使用笔记本读取不到voice文件夹中的音频

请确认文件权限，需要可编辑，如果仅可查看的话应该是无法读取到的。
>上传了三个音频文件，最后自动下载了第一个，其余被忽略了

目前还不支持批量处理文件。今后有可能会考虑有没有好的实现方式。
>我想要批量转化音频，1k-10k这个样子

基本是同一个问题，但批量转换几千上万个音频这样的需求已经大大超过了这个项目的开发目的，可能没有办法考虑支持，抱歉。
