### ISSUE TITLE
话说这个就是最新的Large V3吗？

### ISSUE THREAD

**Issue by MrFutureV** [Ayanaminn/N46Whisper#70]
在huggingface上找到的，应该是这个吗
![QQ截图20231107221453](https://github.com/Ayanaminn/N46Whisper/assets/46783891/a38fddae-b109-4665-a940-76dc7393e3dd)

![QQ截图20231107221001](https://github.com/Ayanaminn/N46Whisper/assets/46783891/9ae51492-0715-4630-a923-d790ae70f2b8)

**Comment by Ayanaminn** [comment]
参见 https://github.com/ggerganov/whisper.cpp/pull/1444
