### ISSUE TITLE
运行提示错误

### ISSUE THREAD

**Issue by MrFutureV** [Ayanaminn/N46Whisper#71]
![QQ截图20231107224642](https://github.com/Ayanaminn/N46Whisper/assets/46783891/420bf33e-c174-4a49-a3a5-60447e9718a6)

**Comment by ShimamuraAdachii** [comment]
在import gc这行下面

**Comment by ShimamuraAdachii** [comment]
在import gc这行下面加上
import torch
就行

**Comment by flywolf53** [comment]
> 在import gc这行下面加上 import torch 就行

我也遇到了这种情况，不过不好意思，import gc是在哪里...

**Comment by ShimamuraAdachii** [comment]
> > 在import gc这行下面加上 import torch 就行
> 
> 我也遇到了这种情况，不过不好意思，import gc是在哪里...

就是这里随便找个地方塞进去都一样
![image](https://github.com/Ayanaminn/N46Whisper/assets/134150279/54f15e8d-71ab-4ffc-bdb6-d34b255dcaad)

**Comment by Ayanaminn** [comment]
修复了这个小问题

**Comment by ShimamuraAdachii** [comment]
> 修复了这个小问题

还有翻译功能也用不了诶 聚聚
