### ISSUE TITLE
字幕翻译功能好像不能用了

### ISSUE THREAD

**Issue by ShimamuraAdachii** [Ayanaminn/N46Whisper#72]
会提示这个 module 'openai' has no attribute 'ChatCompletion'
红线提示的代码是以下的最后一行：
except Exception as e:
            # TIME LIMIT for open api , pay to reduce the waiting time
            sleep_time = int(60 / self.key_len)
            time.sleep(sleep_time)
            print(e, f"will sleep  {sleep_time} seconds")
            # self.rotate_key()
            openai.api_key = self.key
            completion = openai.ChatCompletion.create(

自己瞎查了一通的结果是 这个好像没啥问题啊
就是接入到模型接口里去的功能吧这行代码，然后格式不就是这样的吗
问GPT然后GPT也说是对的，为啥捏

**Comment by Ayanaminn** [comment]
调用api的方式好像变了，我得抽空看看文档做相应的改动

**Comment by ShimamuraAdachii** [comment]
> 调用api的方式好像变了，我得抽空看看文档做相应的改动

好 爱你 我得指着用你这玩意吃饭的（捂脸） 先提前感谢聚聚

**Comment by Ayanaminn** [comment]
有这么夸张吗？这翻译功能只是个半成品哎....
如果你有兴趣分享一下你的使用场景也许能提供更多的帮助，可以发邮件给我

**Comment by ShimamuraAdachii** [comment]
> 有这么夸张吗？这翻译功能只是个半成品哎.... 如果你有兴趣分享一下你的使用场景也许能提供更多的帮助，可以发邮件给我

不管是不是半成品 你这个都是目前最好用的啦
我的使用场景就是单纯的做字幕 一些比较廉价的低要求大量字幕翻译工作 所以就目前的功能能用就是完美啦

非要说的话 虽然我也不懂 而且也不知道实现可能是不是成本太高的一点
我有看到你的默认promote是写了请结合上下文进行翻译这一项的，但实际上翻译出来的东西，上下文是被连贯李姐后被翻译出来了的感觉很弱，
不过总之我也看不懂代码，我也看不出来到底是：
整文本内容提交的（所以是GPT3.5太菜——我自己有改到GPT4尝试跑过一下，瞬间放弃了，30倍的价格实在牛比）
还是单行单行的提交的（那这个就是可能我觉得最做梦都想要的，能改成整文本内容就好了的一点）

粽子现在这样也算很好啦 已经是目前能找到最好用的了

**Comment by ShimamuraAdachii** [comment]
> 有这么夸张吗？这翻译功能只是个半成品哎.... 如果你有兴趣分享一下你的使用场景也许能提供更多的帮助，可以发邮件给我

倒不如说 因为所有工具 包括VAD 断句 之类的 所有功能都已经整合在了这里
对于我这种不懂代码的人来说 要是自己整的话估计根本没戏不知道多费事（走到了部署好faster whisper跑出来了结果这一步为止，死活自己折腾不明白怎么导出srt字幕

然后
我有查了一下，白嫖的COLAB的T4这张显卡，除了用到LARGE模型所需的12G显存满足得比较 相对大众自己买显卡 要轻松很多之外，实际CUDA性能之类的在只用到这样的精度的情况下根本就已经被市面上很多便宜的显卡吊打了吧……虽然还是说回来考虑到LARGE模型的12G需求，可能起步都要从类似3060或者一些老titan之类的卡考虑……

额 就是每次文件量一大 上传到谷歌云盘要超久的
然后文件数量多的话 COLAB白嫖的T4的处理速度就要花好长时间

那 能不能 专门出一个本地运行版本的呢 文件可以直接从本地挑
whisper可以直接调用本地GPU
之前自己尝试了一次 发现COLAB连接到本机运行好像基本上只是需要把那行链接代码输入确认一下就好的简单程度的事
但是这样连接到本地运行后 由于原本的代码是基于上传谷歌云盘以及这个逻辑下之后的一系列操作来写的代码
强行连接到本地好像也没意义

比如说提供一个从本机直接选取本地文件 并且直接调用本地GPU（当然提前准备好够跑的硬件是各自自己需要做好的——既然都自己点到本地运行这里来了——的事情）的页面放在这个github串的介绍里 或者在当前页面里提供相关选项（这个感觉会混淆不是那么明白这些事情的人的视听搞得初次用起来的时候更费解）

**Comment by ShimamuraAdachii** [comment]
> 有这么夸张吗？这翻译功能只是个半成品哎.... 如果你有兴趣分享一下你的使用场景也许能提供更多的帮助，可以发邮件给我

碎碎念有点太啰嗦废话打扰到聚聚的休息时间了主动给聚聚道个歉
这些就当只是闲聊也好啦 能够用到聚聚目前做好给大家用的这样的一整个工具已经非常非常非常心怀感谢了

**Comment by Ayanaminn** [comment]
更新了API调用，现在应该能用了
翻译功能有非常大的优化空间，你说的这些想法也都是可做甚至本来已经打算做的，然而很遗憾，归根结底三个字：没时间

**Comment by ShimamuraAdachii** [comment]
> 更新了API调用，现在应该能用了 翻译功能有非常大的优化空间，你说的这些想法也都是可做甚至本来已经打算做的，然而很遗憾，归根结底三个字：没时间

爱你
