### ISSUE TITLE
这个sakura翻译模型的翻译效果可以接近gpt3.5，请问可以利用google colab接入运行吗？

### ISSUE THREAD

**Issue by fanglangxinghai** [Ayanaminn/N46Whisper#79]
[https://github.com/SakuraLLM/Sakura-13B-Galgame](https://github.com/SakuraLLM/Sakura-13B-Galgame)

如果要做这个事情太麻烦，那就当我没说吧。。。看作者也是挺忙的。

**Comment by Ayanaminn** [comment]
大概看了一眼，colab应该可以搞，但是要给视频字幕翻译合不合适可能就不一定了

**Comment by fanglangxinghai** [comment]
> 大概看了一眼，colab应该可以搞，但是要给视频字幕翻译合不合适可能就不一定了

嗯，我需要的就是单独的colab对文本进行翻译，感觉对于轻小说和漫画的翻译效果应该还不错。
