### ISSUE TITLE
在语音识别库配置完毕，将开始转换这一步出错

### ISSUE THREAD

**Issue by liujianhhy1** [Ayanaminn/N46Whisper#81]
报错如下
![293242376-2544bd9b-0c03-40dd-be09-40cea6ba7e61](https://github.com/Ayanaminn/N46Whisper/assets/73431188/b41e9291-2274-44ca-8ebb-643701ebb65e)
![image](https://github.com/Ayanaminn/N46Whisper/assets/73431188/52ee4715-46ff-43a7-a2bc-c367d4865335)
![image](https://github.com/Ayanaminn/N46Whisper/assets/73431188/f24d6ccf-2095-45a1-93d8-e1104da55926)

**Comment by Ayanaminn** [comment]
这个是因为你可能中间断开过，要重新从第一步执行下去就好
