### ISSUE TITLE
一直显示 加载模型 Loading model...

### ISSUE THREAD

**Issue by 2496414612** [Ayanaminn/N46Whisper#82]
![QQ截图20240103161715](https://github.com/Ayanaminn/N46Whisper/assets/30406907/c70c7139-cefb-4968-9720-7a6155d3f233)

**Comment by ShimamuraAdachii** [comment]
额 我也是 你解决了吗

**Comment by 2496414612** [comment]
> 额 我也是 你解决了吗

没有解决，换用FastWhisperGUI了

**Comment by Ayanaminn** [comment]
后续更新合并到 #84
