### ISSUE TITLE
HF_TOKEN这个是 什么意思 不走了 之前都是好的

### ISSUE THREAD

**Issue by iou3344** [Ayanaminn/N46Whisper#84]
加载模型 Loading model...
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:72: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
model.bin: 100%
3.09G/3.09G [00:31<00:00, 159MB/s]

**Comment by 2496414612** [comment]
这个要你在HF的官网注册一个账号，然后生成一个Token，接着把它填入 Colab 左侧的 secret 栏，并且命名为 HF_Token

**Comment by oasissunderland** [comment]
> 这个要你在Hugging Face的官网注册一个账号，然后生成一个Token，接着把它填入 Colab 左侧的 secret 栏，并且命名为 HF_TOKEN

你成功了吗？为什么我设置了Token 还是有问题，一直卡在加载模型那一步。

**Comment by 2496414612** [comment]
> > 这个要你在Hugging Face的官网注册一个账号，然后生成一个Token，接着把它填入 Colab 左侧的 secret 栏，并且命名为 HF_TOKEN
> 
> 你成功了吗？为什么我设置了Token 还是有问题，一直卡在加载模型那一步。

你要不去看一下 issue#82

**Comment by iou3344** [comment]
from google.colab import userdata
userdata.get('HF_TOKEN')

是不是还需要加这样一句 但不知道要加在哪里

**Comment by 2496414612** [comment]
> from google.colab import userdata
> userdata.get('HF_TOKEN')
> 
> 是不是还需要加这样一句 但不知道要加在哪里

不用加，程序会自动识别你的密钥，加了也没用

**Comment by iou3344** [comment]
还是不行呢，我确定新增了密钥，其他都没改，但就是过不去。
![image](https://github.com/Ayanaminn/N46Whisper/assets/14129104/c9e6e355-e423-482e-98bb-ae4f5e0e5782)

**Comment by iou3344** [comment]
![image](https://github.com/Ayanaminn/N46Whisper/assets/14129104/08932446-e029-48e7-8c9c-098bb7fda3f2)
出现这个时我也允许授权了

**Comment by 2496414612** [comment]
> ![image](https://github.com/Ayanaminn/N46Whisper/assets/14129104/08932446-e029-48e7-8c9c-098bb7fda3f2)
> 出现这个时我也允许授权了

因为这个程序现在本来就不能用，你再怎么设置都是没意义的啊

**Comment by iou3344** [comment]
这个程序现在本来就不能用？什么意思？

**Comment by 2496414612** [comment]
> 这个程序现在本来就不能用？什么意思？

就是不能用了啊，要等作者更新

**Comment by iou3344** [comment]
那我也要谢谢你的指导。唉，用这个都因为缺一块高性能GPU~

**Comment by Ayanaminn** [comment]
这次这个问题大概并不是token的问题。HuggingfaceHub确实几周前[更新](https://github.com/huggingface/huggingface_hub/pull/1912/commits/e0027e5ef18d0e72ec6b01d01f431d7f9baa3333)了遇到没有设置token主动提醒用户以提高安全性，但是这个只是个提醒而已，不会影响后续代码的执行。
现在是卡在这一步执行不下去了
`model = WhisperModel(model_size)`
原因我也还没找到，正在研究

**Comment by Ayanaminn** [comment]
出现一直“加载模型”这个问题的原因是colab更新CUDA 12.2以后没有办法利用GPU了
参见 https://github.com/googlecolab/colabtools/issues/4214

**Comment by Ayanaminn** [comment]
添加了临时解决方案：
https://github.com/Ayanaminn/N46Whisper/commit/bad5a5963ce47d52a9945b55ea26542d17cfd901

**Comment by 2496414612** [comment]
> 添加了临时解决方案：
> https://github.com/Ayanaminn/N46Whisper/commit/bad5a5963ce47d52a9945b55ea26542d17cfd901

作者牛的👍

**Comment by oasissunderland** [comment]
> 添加了临时解决方案： [bad5a59](https://github.com/Ayanaminn/N46Whisper/commit/bad5a5963ce47d52a9945b55ea26542d17cfd901)
谢谢大神

**Comment by iou3344** [comment]
谢谢作者 你们都好了吗？为什么我还得不行，到这里就卡住了
加载模型 Loading model...
config.json: 100%
2.80k/2.80k [00:00<00:00, 215kB/s]

我也首先点了新笔记本中的第一条

Run this cell first!!.
先运行本格，按说明操作！！

**Comment by yuehouqiyou** [comment]
> 谢谢作者 你们都好了吗？为什么我还得不行，到这里就卡住了 加载模型 Loading model... config.json: 100% 2.80k/2.80k [00:00<00:00, 215kB/s]
> 
> 我也首先点了新笔记本中的第一条
> 
> Run this cell first!!. 先运行本格，按说明操作！！

你需要先：
![image](https://github.com/Ayanaminn/N46Whisper/assets/129742191/a3666775-fca5-4cf9-b1ef-665b1f5b07ff)

我可以了
![image](https://github.com/Ayanaminn/N46Whisper/assets/129742191/8d9eca84-8120-4773-b578-17d7d1b7ca47)

**Comment by ShimamuraAdachii** [comment]
牛逼

**Comment by iou3344** [comment]
1）在上方菜单栏选择'工具(tools)' ——> '命令面板(Command palette)
2）输入'使用后备运行时版本(use fallback runtime version)'
3）确认

为什么我的页面上看不到'工具(tools)' ——> '命令面板(Command palette)'

为什么我这么菜 😭

**Comment by iou3344** [comment]
> > 谢谢作者 你们都好了吗？为什么我还得不行，到这里就卡住了 加载模型 Loading model... config.json: 100% 2.80k/2.80k [00:00<00:00, 215kB/s]
> > 我也首先点了新笔记本中的第一条
> > Run this cell first!!. 先运行本格，按说明操作！！
> 
> 你需要先： ![image](https://private-user-images.githubusercontent.com/129742191/294249808-a3666775-fca5-4cf9-b1ef-665b1f5b07ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODk3MDEsIm5iZiI6MTcwNDM4OTQwMSwicGF0aCI6Ii8xMjk3NDIxOTEvMjk0MjQ5ODA4LWEzNjY2Nzc1LWZjYTUtNGNmOS1iMWVmLTY2NWIxZjViMDdmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNzMwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzY0ZjNmYTc0OTJjZTY2MGRiZGIyMjQ3MWQ4OTIxMjY3M2NkMzYyZDk3MDNmM2U2YjhjZDRjMjJiODVhOWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LQGZan_Z2KvilIGP0hxSlV3bPsPVaHQ4e4pDFU5yUjY)
> 
> 我可以了 ![image](https://private-user-images.githubusercontent.com/129742191/294249570-8d9eca84-8120-4773-b578-17d7d1b7ca47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODk3MDEsIm5iZiI6MTcwNDM4OTQwMSwicGF0aCI6Ii8xMjk3NDIxOTEvMjk0MjQ5NTcwLThkOWVjYTg0LTgxMjAtNDc3My1iNTc4LTE3ZDdkMWI3Y2E0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNzMwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTg5ODVlMzE5MjY1N2EyMWY4ZGMyMzg2Mzc4ZjBiNjBmMDJmMTQzNjg3MjUwNTY0NjE2YWVjNDM2Njk2Njk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G0hxTOHhpMGBfLLTLoYgUCxanvQpP6UHuXsviRpz44s)

谢谢 可以了 而且我一开始还犯了一个错误 我以为要输入全部信息 其实只需要输入 使用后备运行时版本 后面英文和括号不需要输入才行 才明白后面的英文是双语的提示~
